# reload config
unbind r
bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."


set -g prefix C-f
set -g mouse on

#removes delay on esc key
set -sg escape-time 0

set -g default-terminal "tmux-256color"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
# set -g @plugin 'rose-pine/tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-yank'

set -g status-position top
setw -g window-status-current-format "#[bold,fg=green]#I:#W"
setw -g window-status-format "#I:#W"
setw -g window-status-style bg=default
setw -g window-status-current-style bg=default

set -g status-bg default
set -g status-left '#[fg=yellow][#S] '
set -g status-style bg=default
set -g status-left-length 30
set -g status-right-length 50
set-option -g status-right ''

setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R


# Set permanent sessions = on
# set -g @continuum-restore 'on'



run '~/.tmux/plugins/tpm/tpm'
