# BACKGROUND
background {
    monitor =
    path = /home/archy/.config/omarchy/current/background
    blur_passes = 1
    blur_size = 1
    brightness = 0.4
    contrast = 1
}

# GENERAL
general {
    no_fade_in = true
    no_fade_out = true
    hide_cursor = false
    grace = 0
    disable_loading_bar = true
}

# INPUT FIELD
input-field {
    monitor = eDP-1
    size = 180, 45
    outline_thickness = 2
    dots_size = 0.28
    dots_spacing = 0.12
    dots_center = true
    dots_rounding = -1
    # outer_color = $primary
    # inner_color = $on_surface
    # font_color = $surface
    fade_on_empty = true
    fade_timeout = 800
    placeholder_text = <i>...</i>
    hide_input = false
    rounding = 40
    check_color = $primary
    fail_color = $error
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 250
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = false
    position = 0, -140
    halign = center
    valign = center
}

# DATE
label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
  color = rgba(242, 243, 244, 0.75)
  font_size = 22
  font_family = TX-02
  position = 0, 300
  halign = center
  valign = center
}

# TIME
label {
  monitor = 
  text = cmd[update:1000] echo "$(date +"%-I:%M")"
  color = rgba(242, 243, 244, 0.75)
  font_size = 95
  font_family = TX-02
  position = 0, 200
  halign = center
  valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(omarchy-what-song)"
    color = rgba(255, 255, 255, 0.8)
    font_size = 13
    font_family = TX-02
    position = 0, 50
    halign = center
    valign = bottom
}
