# smart gaps” / “no gaps when only
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrule = border_size 0, match:float 0, match:workspace w[tv1]
windowrule = rounding 0, match:float 0, match:workspace w[tv1]
windowrule = border_size 0, match:float 0, match:workspace f[1]
windowrule = rounding 0, match:float 0, match:workspace f[1]

#application windowrule

# Scroll nicely in the terminal
windowrule = match:class (Alacritty|kitty), scroll_touchpad 1.5
windowrule = match:class com.mitchellh.ghostty, scroll_touchpad 0.2

windowrule = opacity 1 override 1 override 1 override, match:class firefox
windowrule = opacity 1 override 1 override 1 override, match:class Alacritty
windowrule = opacity 1 override 1 override 1 override, match:class com\.stremio\.stremio
windowrule = opacity 1 override 1 override 1 override, match:class discord
windowrule = opacity 1 override 1 override 1 override, match:class DBeaver
windowrule = workspace 0, match:class Mattermost

#assign workspace 6 to the hdmi
workspace = 6, monitor:HDMI-A-1, default:true

