general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "TX-02", style="medium"}
bold = { family = "TX-02" }
italic = { family = "TX-02" }
size = 10.5

# [colors]
# primary.background = "#141414"

[window]
padding.x = 10
padding.y = 2
decorations = "None"
opacity = 1

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" },
{ key = "Insert", mods = "Shift", action = "Paste" },
{ key = "Insert", mods = "Control", action = "Copy" }
]

# Colors (Dracula)
[colors.primary]
background = '#1C2023'
# foreground = '#f8f8f2'

[colors.cursor]
text = 'CellBackground' # Uses the background color
cursor = "#afd7af"


[colors.normal]
black   = '#2e2e2e'
red     = '#ff7f7f'
green   = '#a5e2a1'
yellow  = '#f7e79c'
blue    = '#b3a0f7'
magenta = '#f2a6d9'
cyan    = '#8bd8f6'
white   = '#dcdcdc'

[colors.bright]
black   = '#575757'
red     = '#ff9999'
green   = '#9ae0b7'
yellow  = '#fff2b3'
blue    = '#cbb3ff'
magenta = '#f4bddf'
cyan    = '#a3e4f9'
white   = '#f0f0f0'

[terminal]
osc52 = "CopyPaste"
