general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "TX-02"}
bold = { family = "TX-02" }
italic = { family = "TX-02" }
size = 11

# [colors]
# primary.background = "#141414"

[window]
padding.x = 10
padding.y = 2
decorations = "None"
opacity = 1

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" },
{ key = "Insert", mods = "Shift", action = "Paste" },
{ key = "Insert", mods = "Control", action = "Copy" }
]
